# -*- coding: utf-8 -*-
"""project.4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EMhoemmjsdfkmTAVGcn5so7iQ9s-nmop
"""

# -*- coding: utf-8 -*-
import streamlit as st
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

# 1. Page Configuration (Must be the very first Streamlit command)
st.set_page_config(
    page_title="Employee Retention Analysis",
    page_icon="🤝",
    layout="wide"
)

# 2. UI Titles & Info
# st.title("Employee Retention Analysis")
# st.write("Predicting employee turnover using Logistic Regression.")
st.markdown("""
<div style="
background:linear-gradient(90deg,#4facfe,#00f2fe);
padding:20px;
border-radius:15px;
text-align:center;
box-shadow:0px 5px 20px rgba(0,0,0,0.3);">

<h1 style="color:white;">
👨‍💼 Employee Retention Analysis Dashboard
</h1>

<h4 style="color:white;">
Predict Employee Turnover using Logistic Regression
</h4>

</div>
""", unsafe_allow_html=True)
st.markdown("---")
st.markdown("""
👨‍💻 **Developed By:** RICHEEK_PANDEY
🔗 **LinkedIn:** [Profile](https://www.linkedin.com/in/richeek-pandey-9954783a9)
💻 **GitHub:** [Repository](https://github.com/richeekpandey07)
""")
# 3. Load dataset safely
import os

try:
    DATA_PATH = os.path.join(
        os.path.dirname(__file__),
        "HR_comma_sep (2).csv"
    )
    df = pd.read_csv(DATA_PATH)

except FileNotFoundError:
    st.error("❌ Error: 'HR_comma_sep (2).csv' not found.")
    st.stop()
# # 3. Load dataset safely
# try:
# #     import os
# # DATA_PATH = os.path.join(os.path.dirname(__file__), "HR_comma_sep (2).csv")
# # df = pd.read_csv(DATA_PATH)
# # except FileNotFoundError:
# #     st.error("❌ Error: 'HR_comma_sep (2).csv' not found. Please place the data file in the same directory as this script.")
# #     st.stop()
#     # st.stop()
#     import os
#  DATA_PATH = os.path.join(os.path.dirname(__file__), "HR_comma_sep (2).csv")
#  df = pd.read_csv(DATA_PATH)

# except FileNotFoundError:
#     st.error("❌ Error: 'HR_comma_sep (2).csv' not found.")
#     st.stop()
# --- DATA EXPLORATION ---
st.header("📊 Data Exploration")

if st.checkbox("Show Raw Data"):
    st.subheader("First few rows of the dataset")
    st.dataframe(df.head())

if st.checkbox("Show Mean Values Grouped by Retention"):
    st.subheader("Average metrics for employees who stayed (0) vs left (1)")
    st.dataframe(df.groupby('left').mean(numeric_only=True))

# --- VISUALIZATIONS (Using Streamlit's Native Charts to avoid Matplotlib Errors) ---
st.header("📈 Data Visualizations")

# Chart 1: Salary vs Retention
st.subheader("Salary vs Employee Retention")
salary_crosstab = pd.crosstab(df['salary'], df['left'])
st.bar_chart(salary_crosstab)

# Chart 2: Department vs Retention
st.subheader("Department vs Employee Retention")
# dept_crosstab = pd.crosstab(df['sales'], df['left'])
# Detect department column automatically
if 'Department' in df.columns:
    dept_col = 'Department'
elif 'department' in df.columns:
    dept_col = 'department'
elif 'sales' in df.columns:
    dept_col = 'sales'
else:
    st.write("Available columns:", df.columns.tolist())
    st.error("Department/Sales column not found!")
    st.stop()

dept_crosstab = pd.crosstab(df[dept_col], df['left'])
st.bar_chart(dept_crosstab)
st.bar_chart(dept_crosstab)
# if 'Department' in df.columns:
#     dept_col = 'Department'
# elif 'sales' in df.columns:
#     dept_col = 'sales'
# else:
#     st.error(f"Department column not found. Available columns: {list(df.columns)}")
#     st.stop()

# dept_crosstab = pd.crosstab(df[dept_col], df['left'])
# st.bar_chart(dept_crosstab)
# --- MODEL TRAINING ---
X = df[['satisfaction_level', 'average_montly_hours', 'promotion_last_5years', 'salary']].copy()

# Encode Salary
le = LabelEncoder()
X['salary'] = le.fit_transform(X['salary'])
y = df['left']

# Split & Train
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# Calculate Accuracy
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

# Sidebar Metrics
st.sidebar.header("🤖 Model Performance")
st.sidebar.metric(label="Model Accuracy", value=f"{accuracy:.2%}")

# --- INTERACTIVE PREDICTION ---
st.markdown("---")
st.header("🔮 Predict Employee Retention")
st.write("Input the employee's details below to predict turnover risk:")

satisfaction = st.slider("Satisfaction Level", min_value=0.0, max_value=1.0, value=0.5, step=0.01)
hours = st.number_input("Average Monthly Hours", min_value=10.0, max_value=400.0, value=200.0, step=1.0)
promotion = st.selectbox("Promoted in last 5 years?", options=["No", "Yes"])
salary_input = st.selectbox("Salary Level", options=list(le.classes_))

# Convert inputs for the model
promotion_val = 1 if promotion == "Yes" else 0
salary_val = le.transform([salary_input])[0]

if st.button("Predict"):
    input_data = pd.DataFrame([[satisfaction, hours, promotion_val, salary_val]],
                              columns=['satisfaction_level', 'average_montly_hours', 'promotion_last_5years', 'salary'])

    prediction = model.predict(input_data)[0]
    probability = model.predict_proba(input_data)[0][1]

    if prediction == 1:
        st.error(f"⚠️ Warning: The employee is likely to **LEAVE**. (Risk Probability: {probability:.2%})")
    else:
        st.success(f"✅ Success: The employee is likely to **STAY**. (Retention Probability: {(1-probability):.2%})")
